### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ArnaudBarre** [vobyjs/voby-esbuild#1]
Hi, just read the features list and I like to see the exploration into client-first + no transpiler magic, making it potentially compatible with raw perf of esbuild. So I'm surprised to see that you need to hook into every TSX file in this plugin and I'm curious from what prevents you to directly use the inject option?

**Comment by fabiospampinato** [comment]
Nothing prevents you from using esbuild/tsc/vite directly, this package is kind of a placeholder for potential future features, it might just get deleted.
